# Generated by Django 5.1.1 on 2024-09-30 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_wishlistitem_user_alter_wishlistitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='WishlistItem',
        ),
    ]
