# Generated by Django 5.1.1 on 2024-09-26 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profileImage/no-profile-picture.png', upload_to='profileImage'),
        ),
    ]
